<a href="https://colab.research.google.com/github/wjdgoruds2/Machine_Learning/blob/main/Bernoulli_Na%C3%AFve_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np#배열 사용
import pandas as pd #데이터 분석을 위한 pandas
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB#베르누이 단순 베이즈 분류기
from sklearn.metrics import accuracy_score#정확도 평가

email_list=[{'title':'free game only today','spam':True}, #데이터 6개 표현
            {'title':'cheapest flight deal','spam':True},
            {'title':'limited time offer only today only today','spam':True},
            {'title':'your flight schedule attached','spam':False},
            {'title':'today meeting schedule','spam':False},
            {'title':'your credit card statement','spam':False},]
df=pd.DataFrame(email_list)#email_list로 데이터 프레임 생성

df['label']=df['spam'].map({True:1,False:0})#spam의 True,False구분
df_x=df['title']#x축설정
df_y=df['label']#y축 설정
print("**데이터**\n",df)

cv=CountVectorizer(binary=True)#단어들의 카운트로 카툰트 행렬
x_traincv=cv.fit_transform(df_x)#평균과 표준편차 계산후 정규화
print('\n변환된 데이터 표현(1~2번째 이메일)**\n',x_traincv[0:2])#1~2번째 메일 분석 출력

encoded_input=x_traincv.toarray()#배열 반환
print('\n**이진 벡터 표현 **\n',encoded_input)#배열 출력

print('\n**벡터 위치별 대응 단어 **\n',cv.get_feature_names())#feature단어 목록 보기
print('\n**첫번째 벡터에 대응하는 단어들 **\n',cv.inverse_transform(encoded_input[0]))#첫번째 행렬
Bnb=BernoulliNB()#베르누이 분류기
y_train=df_y.astype('int')#숫자형으로 바꾸기
Bnb.fit(x_traincv,y_train)#평균과 표준편차 구함

test_email_list=[{'title':'free flight offer','spam':True},#test데이터 6개 생성
            {'title':'hey traveler free flight deal','spam':True},
            {'title':'limited free game offer','spam':True},
            {'title':'today flight schedule','spam':False},
            {'title':'your credit card attached','spam':False},
            {'title':'free credit card offer only today','spam':False},]

test_df=pd.DataFrame(test_email_list)#test_email_list로 데이터 프레임 생성
test_df['label']=test_df['spam'].map({True:1,False:0})#spam의 True,False구분
test_x=test_df['title']#x축설정
test_y=test_df['label']#y축 설정
x_testcv=cv.transform(test_x))#평균과 표준편차 계산후 정규화

predicted_y=Bnb.predict(x_testcv)#x_testcv사용 예측 값 계산
print("\n Predicted Label **\n",predicted_y)
accuracy=accuracy_score(test_y,predicted_y)#정확도 계산
print('\nAccuracy=',accuracy)


**데이터**
                                       title   spam  label
0                      free game only today   True      1
1                      cheapest flight deal   True      1
2  limited time offer only today only today   True      1
3             your flight schedule attached  False      0
4                    today meeting schedule  False      0
5                your credit card statement  False      0

변환된 데이터 표현(1~2번째 이메일)**
   (0, 6)	1
  (0, 7)	1
  (0, 11)	1
  (0, 15)	1
  (1, 2)	1
  (1, 5)	1
  (1, 4)	1

**이진 벡터 표현 **
 [[0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0]
 [0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1]]

**벡터 위치별 대응 단어 **
 ['attached', 'card', 'cheapest', 'credit', 'deal', 'flight', 'free', 'game', 'limited', 'meeting', 'offer', 'only', 'schedule', 'statement', 'time', 'today', 'your']

**첫번째 벡터에 대응하는 단어들 **
 [array(['free', 'game', 'only',